"""Baseline schema — VERSION 2.

A frozen snapshot of the Betelgeuse schema as of the introduction of the migration
framework. It folds the whole pre-framework schema (v1 + the v2 watch-fields/transactions
change) into one step, so a brand-new DB built by running migrations from scratch ends up
byte-identical to what `init_db()`'s new-DB branch produced before.

**Do not edit this file.** Future schema changes are new `003_*.py`, `004_*.py`, … modules.
It creates only the *data* tables; the framework's own `db_meta` / `schema_migrations` infra
tables are created by `core.migrate.ensure_infra()`, not here (chicken-and-egg).
"""
from core.migrate import Irreversible

VERSION = 2
DESCRIPTION = "baseline schema (portfolio, settings, static-data + OHLCV caches, transactions)"

_DEFAULT_SETTINGS = {
    'url_template_3m': 'https://charts.aastocks.com/servlet/Charts?stockid={stockid}&period=4&type=1',
    'url_template_6m': 'https://charts.aastocks.com/servlet/Charts?stockid={stockid}&period=5&type=1',
    'url_template_1y': 'https://charts.aastocks.com/servlet/Charts?stockid={stockid}&period=6&type=1',
    'url_template_1y_monthly': 'https://charts.aastocks.com/servlet/Charts?stockid={stockid}&period=7&type=1',
}


def up(c):
    c.execute('''
        CREATE TABLE IF NOT EXISTS portfolio (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            market TEXT NOT NULL,
            name TEXT NOT NULL,
            "group" TEXT DEFAULT 'Default',
            added_date TEXT NOT NULL,
            comment TEXT,
            monitor_price REAL,
            trigger_price REAL,
            bought INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    c.execute('''
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT
        )
    ''')
    for key, value in _DEFAULT_SETTINGS.items():
        c.execute('INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)', (key, value))
    c.execute('''
        CREATE TABLE IF NOT EXISTS hk_securities (
            stock_code TEXT PRIMARY KEY,
            name TEXT,
            category TEXT,
            sub_category TEXT,
            board_lot TEXT
        )
    ''')
    c.execute('''
        CREATE TABLE IF NOT EXISTS crypto_ohlcv (
            source TEXT DEFAULT 'coingecko',
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            coin_id TEXT NOT NULL,
            period TEXT NOT NULL,
            timestamp INTEGER NOT NULL,
            open REAL, high REAL, low REAL, close REAL,
            fetched_at TEXT NOT NULL,
            UNIQUE(coin_id, period, timestamp, source)
        )
    ''')
    c.execute('''
        CREATE TABLE IF NOT EXISTS coingecko_coins (
            coin_id TEXT PRIMARY KEY,
            symbol TEXT,
            name TEXT,
            market_cap_rank INTEGER
        )
    ''')
    c.execute('CREATE INDEX IF NOT EXISTS idx_coingecko_symbol ON coingecko_coins(symbol)')
    c.execute('''
        CREATE TABLE IF NOT EXISTS us_securities (
            symbol TEXT NOT NULL,
            name TEXT,
            board TEXT NOT NULL,
            etf INTEGER DEFAULT 0,
            PRIMARY KEY (symbol, board)
        )
    ''')
    c.execute('CREATE INDEX IF NOT EXISTS idx_us_symbol ON us_securities(symbol)')
    c.execute('''
        CREATE TABLE IF NOT EXISTS stock_ohlcv (
            source TEXT DEFAULT 'yfinance',
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            market TEXT NOT NULL,
            symbol TEXT NOT NULL,
            timestamp INTEGER NOT NULL,
            open REAL, high REAL, low REAL, close REAL,
            currency TEXT,
            fetched_at TEXT NOT NULL,
            UNIQUE(source, market, symbol, timestamp)
        )
    ''')
    c.execute('CREATE INDEX IF NOT EXISTS idx_stock_ohlcv ON stock_ohlcv(market, symbol)')
    c.execute('''
        CREATE TABLE IF NOT EXISTS transactions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            market TEXT NOT NULL,
            symbol TEXT NOT NULL,
            txn_type TEXT NOT NULL DEFAULT 'buy',
            price REAL NOT NULL,
            quantity REAL NOT NULL,
            txn_date TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    c.execute('CREATE INDEX IF NOT EXISTS idx_txn_instrument ON transactions(market, symbol)')


def down(c):
    raise Irreversible(
        "002_baseline is the baseline schema and cannot be reverted "
        "(it would drop the source-of-truth portfolio/transactions). "
        "Restore a pre-migration backup instead.")
